version: '3'

services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEV_DB=aghcampus_dev
      - TEST_DB=aghcampus_test
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"